### ISSUE TITLE
Do not install optional dependencies

### ISSUE THREAD

**Issue by Real-Gecko** [anntzer/pypi2pkgbuild#27]
I've created package for https://pypi.org/project/djlint/ and it added optional dependencies as normal dependencies.

Take a look at here:
https://github.com/Riverside-Healthcare/djLint/blob/master/pyproject.toml

```toml
coverage = { version = "^6.3.1", optional = true }
pytest = { version = "^7.0.1", optional = true }
pytest-cov = { version = "^3.0.0", optional = true }
```

![image](https://user-images.githubusercontent.com/2231969/181703892-8051de67-0b36-4efd-909c-83131d69d942.png)

As you can see they're not marked as optional during installation.
